### ISSUE TITLE
Record conversion not working as expected

### ISSUE THREAD

**Issue by philhutch50** [paolo-rossi/delphi-neon#13]
I Have a record with arrays inside it as follows..

And get an Insufficient RTTI support?

Thanks
Phil

**Comment by paolo-rossi** [comment]
Hi Phil,

if you have a static array then you are out of luck because Delphi doesn't generate RTTI information for static arrays. 
The only way is to use a Custom Serializer to serialize your array.

Paolo.

**Comment by philhutch50** [comment]
Thanks @paolo-rossi  for the reply.  I hit same issue on other serialisers so realised after writing this it was a delphi RTTI problem.
