### ISSUE TITLE
TTime Serialization

### ISSUE THREAD

**Issue by hafedh-trimeche** [paolo-rossi/delphi-neon#24]
The **TTime** is serialized as **TDateTime**.

**12:15:00** is serialized as **1899-12-30T12:15:00.000Z** instead of **12:15:00**.

Best regards.

**Comment by paolo-rossi** [comment]
Hi @hafedh-trimeche,

I use the ISO8601 for the Date/Time output and there is no way to specify only the Time portion with the ISO8601 standard. 

Fortunately you can (easily) build a custom serializer for that, I will update the main Demo to include such serializer as an example.

Ciao,
Paolo.

**Comment by hafedh-trimeche** [comment]
Hello Paolo,

Is it possible to include into serialized Json only fields having values different from default (Empty) ones: 0, '', [], ...

Please find a TTime Serializer:
```
  TTimeSerializer = class(TCustomSerializer)
  protected
    class function GetTargetInfo:PTypeInfo;override;
    class function CanHandle(AType:PTypeInfo):Boolean;override;
  public
    function Serialize(const AValue:TValue;ANeonObject:TNeonRttiObject;AContext:ISerializerContext):TJSONValue;override;
    function Deserialize(AValue:TJSONValue;const AData:TValue;ANeonObject:TNeonRttiObject;AContext:IDeserializerContext):TValue;override;
  end;

class function TTimeSerializer.GetTargetInfo:PTypeInfo;

begin
  Result := TypeInfo(TTime);
end;

class function TTimeSerializer.CanHandle(AType:PTypeInfo):Boolean;
begin
  Result := (AType=GetTargetInfo);
end;

function TTimeSerializer.Serialize(const AValue:TValue;ANeonObject:TNeonRttiObject;AContext:ISerializerContext):TJSONValue;
var
  LTime : TTime;
begin
  LTime  := AValue.AsType<TTime>;
	Result := TJSONString.Create(FormatDateTime('hh:nn:ss.zzz',LTime));
end;

function TTimeSerializer.Deserialize(AValue:TJSONValue;const AData:TValue;ANeonObject:TNeonRttiObject;AContext:IDeserializerContext):TValue;
var
  LTime : TDateTime;
  FS    : TFormatSettings;
begin
  FS                   := default(TFormatSettings);
  FS.DateSeparator     := '-';
  FS.TimeSeparator     := ':';
  FS.LongDateFormat    := 'yyyy-mm-dd';
  FS.LongTimeFormat    := 'hh:nn:ss.zzz';
  FS.ThousandSeparator := ' ';
  FS.DecimalSeparator  := '.';
  if not TryStrToTime(AValue.Value,LTime,FS) then LTime := -1;
  Result := TValue.From(LTime);
end;

```
Best regards.

**Comment by JensMertelmeyer** [comment]
> there is no way to specify only the Time portion with the ISO8601 standard

I'm not quite sure that is correct. Does ISO8601 have to include a date? I believe it can just be a time:
https://tools.ietf.org/html/rfc3339#appendix-A

Serializing a `TTime` as time instead of a `TDateTime` could be a valid use case.
