### ISSUE TITLE
Empty fields

### ISSUE THREAD

**Issue by hafedh-trimeche** [paolo-rossi/delphi-neon#27]
Hello,

Is it possible to include into serialized Json only fields having values different from default (Empty) ones: 0, '', [], ...

Best regards.

**Comment by paolo-rossi** [comment]
Hi @hafedh-trimeche 

Yes, it's possible.. please look at the attributes:
[NeonInclude(IncludeIf.NotDefault)] and [NeonInclude(IncludeIf.NotEmpty)]

Paolo.

**Comment by hafedh-trimeche** [comment]
Hi,

Thanks for your support.

I'm looking for configuration parameter which is when set avoids writing **Default** values not per field's **attribute**.

**TNeonConfiguration.WriteNotDefault : Boolean** would be used as global configuration for Json output.

Best regards.
