### ISSUE TITLE
Memory leak on Nullable<class>

### ISSUE THREAD

**Issue by dualarrow** [paolo-rossi/delphi-neon#34]
Hi, Great library. Does way more than all the others !

If I create a property like
property Prop: Nullable\<TObject\> read FProp write FProp;
and in the constructor have
FProp := TObject.Create;
if I assign nil to the property in my code like

var x: TMyData;
x := TMyData.Create;   // constructor creates instance of TObject for FProp
x.Prop := nil;

x.Prop is not freed. I could free it manually, but in the TNeon.JSONToObject I don't get that opportunity and the object leaks. eg, Json string is
{}
ie there is no Prop in the JSON string. This creates the object correctly but rather than having a nil value for Prop, it has a TObject there and the HasValue property for Prop is true even though it had no value in the JSON.

I looked at the available attributes and couldn't find one that would solve this. Is this a bug or have I done something wrong ?

I think I can get around it by processing the JSON objects and removing any TJsonClass entries that have nothing in them.

MORE DETAIL

It seems the constructor works as expected, so no problem there. It also seems the correct way to destroy a Nullable\<TObject\> in the destructor is
if FProp.HasValue then
  TObject(FProp).Free;

and to assign a nil to the property
TObject(x.Prop).Free;
x.Prop := nil;

and to assign a new non-nil object

TObject(x.Prop).Free;
x.Prop := TObject.Create;

If I make sure I do all this, then no leaks occur.

**Comment by JensMertelmeyer** [comment]
Maybe I didn't have enough coffee ☕ today, but I don't understand how Nullable<TObject> makes sense. Reference types are already nullable, what purpose does it solve to make them "_double-nullable_"?

**Comment by dualarrow** [comment]
You had me rechecking my tests. After rechecking, I found that making an object nullable seemed to make it load up correctly.

If I have 2 classes defined like this

type
  TJunk = class
  private
    FAnInt: integer;
  public
    property AnInt: integer read FAnInt write FAnInt;
  end;

  TTest = class
  private
    FSomeDate: TDate;
    FSomeTime: TTime;
    FSomeDateTime: TDateTime;
    FJunk: TJunk;
  public
    constructor create;

    property someDate: TDate read FSomeDate write FSomeDate;
    property someTime: TTime read FSomeTime write FSomeTime;
    property someDateTime: TDateTime read FSomeDateTime write FSomeDateTime;
    property Junk: TJunk read FJunk write FJunk;
  end;

if TTest is created, and the constructor doesn't create an instance of TJunk, then if I create my own instance and assign it, then serialize it to a string, then deserialize the string back to an object, then the Junk property has nil in it and not an instance of TJunk.

If the constructor creates and instance of TJunk, then if I assign a nil to the Junk property, then serialize it. When I deserialize it, instead of having a nil in it, it has the freshly created instance from the constructor.

By making the Junk property a Nullable<TJunk> it seems to serialize and deserialize correctly.

As per my initial report, if I just assign a nil to a Nullable<TJunk> that was created in the constructor, then the Nullable class just assigns the nil to the field without freeing it. It works correctly if I manually free it then assign either a nil or another instance to it.

The code I was using in my testing can be found here https://pastebin.com/5jAQLcRk but it also has some custom serializers I was working on in it too, but other than that, the example shown demonstrates the constructor creating the instance, then assigning a nil to the Junk property, serializing and then deserializing the class. If you then inspect the object "o", you'll see it contains an instance of TJunk when it was serialized with a nil.

I hope that makes sense. It was a bit of an odd one to describe.
