### ISSUE TITLE
Return null instead of empty in Tdatatime

### ISSUE THREAD

**Issue by UpperSoftwares** [paolo-rossi/delphi-neon#36]
function TNeonSerializerJSON.WriteDate(const AValue: TValue; ANeonObject: TNeonRttiObject): TJSONValue;
begin
  case ANeonObject.NeonInclude.Value of
    IncludeIf.NotEmpty, IncludeIf.NotDefault:
    begin
      if AValue.AsExtended = 0 then
        Exit(nil);
    end;
  end;

  **if AValue.AsType<TDateTime> <> 0 then
    Result := TJSONString.Create(TJSONUtils.DateToJSON(AValue.AsType<TDateTime>, FConfig.UseUTCDate))
  else
    Result := TJSONNull.Create;**
end;

**Comment by paolo-rossi** [comment]
Hi,

thank you for trying Neon, now for the issue:

I think that regarding date & time management the best course of action would be a custom serializer so you can do everithing you want, please look at the file linked to see an example of a TDateTime custom serializer:
https://github.com/paolo-rossi/delphi-neon/blob/7edf60bb35dca9b1609488cbd4574abfae5d1415/Demos/Main/Demo.Neon.Serializers.pas#L107

Paolo.
