### ISSUE TITLE
Source\Neon.Core.Persistence.Swagger.pas is missing

### ISSUE THREAD

**Issue by KoruNL** [paolo-rossi/delphi-neon#38]
As far as I can see the source Source\Neon.Core.Persistence.Swagger.pas is missing.
Regards, Jan.

**Comment by paolo-rossi** [comment]
Hi @KoruNL ,

I renamed that unit, that is now: Neon.Core.Persistence.JSON.Schema.pas

Ciao,
Paolo.

**Comment by KoruNL** [comment]
Hi Paolo,
OK, that might be the case, but Source\Neon.Core.Persistence.Swagger.pas is still used in the dpk-files.
Thanx for a great component, Jan.

**Comment by paolo-rossi** [comment]
Hi @KoruNL ,

You are right, I always forgot to update the dpk files! will do ASAP..

Paolo.
