### ISSUE TITLE
Access violation using Enumerated Types with Explicitly Assigned Ordinality

### ISSUE THREAD

**Issue by Himhotep** [paolo-rossi/delphi-neon#4]
To test it you only have to change
TEnumSpeed = (Low, Medium, High);
to 
TEnumSpeed = (Low=1, Medium=2, High=3);
in Demo.Neon.Entities unit. Then press TMyRecord button.

**Comment by paolo-rossi** [comment]
Hi there,

sorry it took me so long to reply... anyway, regarding the issue:

Delphi does not generate Rtti information for enum types with explicit ordinality, to verify please write this line in both cases:

```
var
  LSpeedType TRttiType;
begin
  LSpeedType := LContext.GetType(TypeInfo(TEnumSpeed));
```

You'll see that in the second case Delphi complains that:

`[dcc32 Error] Unit3.pas(50): E2134 Type 'TEnumSpeed' has no type info`

So, I'm afraid I will not be able to serialize these type of enum, but regarding the access violation, I will try to handle the returning nil TRttiType skipping the particular member.

Ciao,
Paolo.
