### ISSUE TITLE
Access violation in Main demo

### ISSUE THREAD

**Issue by holgerflick** [paolo-rossi/delphi-neon#50]
Main demo throws Access violation for Dictionary

![image](https://user-images.githubusercontent.com/1275944/178302372-8c0eb3ec-f1b3-4f13-a49d-5c65d350ddf9.png)

**Comment by holgerflick** [comment]
I am unable to reproduce after recompile, but I still get a memory leak:

![image](https://user-images.githubusercontent.com/1275944/178303071-51c82542-6610-45dc-9068-212b4a95a86e.png)

**Comment by paolo-rossi** [comment]
Hi @holgerflick 

I tried right now with Delphi 11 and Delphi 10.2 and it seems to run without errors and without memory leaks (I also tried the deserialization). Can you tell me what Delphi version are you using? Or the changes you made for the sample? Thanks!

Ciao,
Paolo.

**Comment by paolo-rossi** [comment]
I will close this issue, if you have some suggestions please use the [discussion](https://github.com/paolo-rossi/delphi-neon/discussions) tab here in GitHub
