### ISSUE TITLE
How do I use Arrays and Records ?

### ISSUE THREAD

**Issue by mgcd-jed** [paolo-rossi/delphi-neon#53]
Passing a record to TNeon.ObjectToJSON doesn't work, and a class containing an array will not be completely serialised (the array field won't even be in the JSON).

**Comment by paolo-rossi** [comment]
Hi @mgcd-jed 

in order to serialize records you must use the TNeon.ValueToJSON method. Speaking of array Neon (but I can say Delphi) doesn't support static arrays because there is no Rtti info generated for this type. Dynamic arrays are fully supported though..
If you have some problem with your code please show me the class/record you are trying to work with.

Ciao,
Paolo.

**Comment by mgcd-jed** [comment]
Hey @paolo-rossi , thanks for answering !
Here's an example code :

```pascal
program Project1;

uses
  Neon.Core.Persistence.JSON,
  System.Rtti;

type
  TArr = Array [0..2] of Integer;
  TARecord = record
    data1: Integer;
    data2: Integer;
    data3: TArr;
  end;
  
var
  myRecord : TARecord;
  s: string;
begin
  myRecord.data1 := 1;
  myRecord.data2 := 2;
  myRecord.data3[0] := 1;   
  myRecord.data3[1] := 2;
  myRecord.data3[2] := 3;

  Writeln(TNeon.ValueToJSONString(TValue.From<TARecord>(myRecord)));
  Readln(s);
end.
```

The output ends up being `'{"data1":1,"data2":2}'` with an exception about insufficient RTTI info, like you said. if the TArr isn't declared.
Is this the only workaround known or is there a better way of doing things ?

**Comment by mgcd-jed** [comment]
That's pretty cool when it comes to small records/classes, but when the thing has dozens of variables, manually making a serialization is just asking to create bugs. I think I'll have to go with the `TArr` approach.
Though it could be worth investigating if Delphi has some sort of attribute or compiler directive telling it to generate RTTI for static arrays, since it obviously can (as shown with my example above), it just doesn't unless it's linked to a named type.
Maybe a compiler directive could simply create the relevant type at compile time so RTTI gets generated afterwards.

Thanks for the help :)

**Comment by paolo-rossi** [comment]
@mgcd-jed 

Yeah, if the static array is not a named type then you are out of luck...

>Though it could be worth investigating if Delphi has some sort of attribute or compiler directive telling it to generate RTTI for 
>static arrays, since it obviously can (as shown with my example above), it just doesn't unless it's linked to a named type.
>Maybe a compiler directive could simply create the relevant type at compile time so RTTI gets generated afterwards.

I didn't find anything useful but you you find something please let me know!

Paolo.
