### ISSUE TITLE
Not compatible with XE7

### ISSUE THREAD

**Issue by GitCnSH-DSLIN** [paolo-rossi/delphi-neon#59]
For example, There is no TJsonBool object in XE7.

**Comment by paolo-rossi** [comment]
Yes you are right, I will amend the README, although it's probably the only thing that is not compatible with XE7 but I consider the lack of a proper TJSONBool a nasty hole for a JSON library. Furthermore I don't have anymore XE7 installed on my PC so I cannot test a proper workaround... (I was thinking of adding a TJSONBool type in < XE7)

If you want to submit a PR to fix that, you are welcome!

Ciao,
Paolo.
