### ISSUE TITLE
Insufficient RTTI available

### ISSUE THREAD

**Issue by hafedh-trimeche** [paolo-rossi/delphi-neon#66]
Hello,

Please note that this exception is raised when this record needed to be serialized:
  ```
TFaceLandmark =
  record
    KeyPoints : array[1..68] of TPointFloat;
  end;
```
`Project raised exception class EInsufficientRtti with message 'Insufficient RTTI available to support this operation'.
`

Best regards.

**Comment by paolo-rossi** [comment]
Hello @hafedh-trimeche 

I know, Delphi does not generate RTTI info for static arrays. I see 2 options to that:

1. Change the type to a dynamic array
2. Name the static array type and Build a custom serializer for that type

Ciao,
Paolo.
