### ISSUE TITLE
request

### ISSUE THREAD

**Issue by achinastone** [paolo-rossi/delphi-neon#79]
Can I set the number of decimal places for persistence?

**Comment by paolo-rossi** [comment]
Hello, @achinastone ,

I'm using the TJSON* classes and the .ToJSON standard function to convert values to and from so I don't think there is a way to do that with the Delphi System.JSON unit (as far as I know)

Paolo.

**Comment by achinastone** [comment]
Thanks for your reply. I use DDetours hook the FloatToText in System.JSON.
