### ISSUE TITLE
Multithreading is prone to problems

### ISSUE THREAD

**Issue by achinastone** [paolo-rossi/delphi-neon#83]
I found a bad design style in the code, which forcibly converts IInterface to TObject and stores it.
e.g.
`
constructor TNeonBase.Create(const AConfig: INeonConfiguration);
begin
  FConfig := AConfig as TNeonConfiguration;
  FMemberRegistry := TMemberRegistry.Create([doOwnsValues]);
  FErrors := TStringList.Create;
end;
`
If temporary variables are used externally to save this interface, it is likely that the FConfig object will be released in subsequent use due to a zero reference count.

Actually, even if it's not multi-threaded, it's easy to encounter problems

**Comment by paolo-rossi** [comment]
Thanks @achinastone!
